import Link from "next/link";
import { getRequestLocale } from "@/lib/i18n/server";
import LanguageSwitcher from "@/app/LanguageSwitcher";
import styles from "./system-process.module.css";

type Section = { title: string; label: string; paragraphs: string[]; quote: string; sourceTitle: string; source: string };
type Copy = {
  brand: string; nav: string; eyebrow: string; title: string; question: string; judgment: string;
  asideTitle: string; asideBody: string; compareTitle: string; compareTag: string;
  systemLabel: string; systemHeading: string; realLabel: string; realHeading: string;
  system: readonly (readonly [string, string])[]; real: readonly (readonly [string, string])[];
  sections: Section[]; links: string[]; conclusion: string; ending: string; boundary: string; back: string; footer: string;
};

const zhSections: Section[] = [
  { title: "判断不是点击", label: "判断 / 不是点击", paragraphs: ["系统可以要求用户选择门店、填写字段、提交审批，但它通常不知道现场问题究竟属于哪种情况。真实业务中的第一步，往往不是点击“开始”，而是判断问题是否成立、应该走哪条路径、需要谁参与。", "如果产品只把标准动作配置成固定步骤，用户遇到特殊情况时就会寻找替代方式：线下沟通、口头确认、重复提交，或者让熟悉规则的人直接介入。系统看起来完成了流程，组织却没有获得更好的判断能力。"], quote: "流程不是把动作排列起来，而是让组织知道下一步为什么这样做。", sourceTitle: "繁琐的评分活动", source: "门店陈列需要综合 SKU、排面、位置、价格和货龄判断。若只是把复杂计算搬到一线，系统完成了配置，却没有减少判断负担。" },
  { title: "例外不是错误", label: "例外 / 不是错误", paragraphs: ["渠道、组织和门店关系持续变化，标准流程不可能提前写完所有情况。一个系统如果只强调规则完整，却没有给业务留下反馈和修正的入口，例外就会从流程里消失，转移到系统外。", "这也是为什么很多功能问题反复出现：用户看到的是权限不对、门店不可见、流程无法继续；真正需要被理解的，可能是组织关系、门店归属和业务责任发生了变化。"], quote: "好的流程不是没有例外，而是例外能够被识别、承接并反过来修正规则。", sourceTitle: "门店看不到，背后是关系没被表达", source: "定位组织与门店关系、提出关系模型改造方案，再协调业务和研发推动上线，问题才从权限配置回到业务关系。" },
  { title: "责任不是状态", label: "责任 / 不是状态", paragraphs: ["销售、经销商、职能部门和研发可以同时出现在一套系统里，但如果没有明确谁发现问题、谁判断、谁处理、谁反馈，系统中的状态变化只会替代沟通，并不会形成真正的责任链。", "产品设计需要把这些关系显性化：让问题有去处，让反馈能回流，让管理者知道哪些规则需要调整。系统不是把人变成流程，而是让复杂的协作关系能够被看见和持续调整。"], quote: "好的系统不是消灭人的判断，而是让判断、协同与责任能够被组织起来。", sourceTitle: "从功能问题回到业务关系", source: "需求梳理、关系模型、研发协调、测试上线和问题跟踪，最终解决的不是一个页面，而是一条责任关系。" },
];

const copy: Record<"zh-CN" | "en" | "ja", Copy> = {
  "zh-CN": { brand: "现代工作笔记", nav: "FMCG FIELD NOTES / 02", eyebrow: "FMCG BUSINESS & SYSTEM DESIGN", title: "系统不等于业务闭环", question: "为什么系统里的步骤都对，到了现场却仍然需要反复解释、协调和绕行？", judgment: "系统可以承载流程，但不能自动生成流程。真实流程还包括判断、例外处理、角色协同和责任承接。", asideTitle: "这篇文章讨论什么？", asideBody: "系统里的步骤都正确，为什么到了现场仍然需要解释、协调和绕行？", compareTitle: "系统记录的是步骤，真实业务运行的是关系。", compareTag: "SYSTEM / PROCESS", systemLabel: "系统里的流程", systemHeading: "可以被配置的步骤", realLabel: "真实的流程", realHeading: "需要被组织承接的关系", system: [["提交", "完成字段填写，进入下一节点。"], ["审批", "按照规则分配与处理。"], ["完成", "状态变为已结束。"]], real: [["判断", "这是什么问题，是否应该进入这条流程？"], ["例外", "标准规则无法覆盖时，谁来决定如何处理？"], ["责任", "谁承接结果，谁反馈变化，谁继续调整？"]], sections: zhSections, links: ["展开 SFA 实践证据 ↗", "查看权限治理证据 ↗", "打开项目证据空间 ↗"], conclusion: "系统的边界，不是能力不足，而是它不能替组织完成理解与协同。", ending: "数字化产品真正要做的，不是把所有事情都固化成按钮，而是把业务关系表达清楚，让标准流程能够运行，让例外能够被承接，让责任能够继续向前传递。", boundary: "公司、品牌和内部系统细节匿名；文章基于真实项目经验进行行业抽象。", back: "← 回到工作首页", footer: "流程被写进系统之前，先要被业务真正理解。" },
  en: { brand: "Modern Field Notes", nav: "FMCG FIELD NOTES / 02", eyebrow: "FMCG BUSINESS & SYSTEM DESIGN", title: "A System Is Not a Business Loop", question: "Why can every step be correct in the system, while the field still needs explanation, coordination, and workarounds?", judgment: "A system can carry a process, but it cannot create one by itself. A real process also includes judgment, exceptions, role coordination, and ownership.", asideTitle: "What is this note about?", asideBody: "Why do correct system steps still require explanation, coordination, and workarounds in the field?", compareTitle: "A system records steps. The business actually runs on relationships.", compareTag: "SYSTEM / PROCESS", systemLabel: "The system process", systemHeading: "Configurable steps", realLabel: "The real process", realHeading: "Relationships the organization must carry", system: [["Submit", "Complete the fields and move to the next step."], ["Approve", "Route and handle the request by rule."], ["Complete", "The status changes to finished."]], real: [["Judge", "What is the issue, and should it enter this process?"], ["Exception", "When the standard rule does not apply, who decides what happens?"], ["Own", "Who carries the result, feeds back the change, and keeps adjusting?"]], sections: [
    { title: "Judgment Is Not a Click", label: "JUDGMENT / NOT A CLICK", paragraphs: ["A system can ask users to select a store, fill in fields, and submit an approval. It usually cannot tell what the field issue really is. In real work, the first step is often not clicking “Start”, but deciding whether the issue is real, which path it belongs to, and who needs to join.", "When a product turns only standard actions into fixed steps, people look for alternatives when exceptions appear: offline conversations, verbal confirmation, repeated submissions, or direct intervention from someone who knows the rules. The system appears to complete the process, but the organization has not gained better judgment."], quote: "A process does not merely arrange actions; it helps the organization understand why the next action is needed.", sourceTitle: "A cumbersome scoring activity", source: "Store display quality required a combined view of SKUs, shelf positions, placement, price, and product age. Moving complex calculations to the frontline completed the configuration, but did not reduce the judgment burden." },
    { title: "Exceptions Are Not Errors", label: "EXCEPTIONS / NOT ERRORS", paragraphs: ["Channel, organization, and store relationships keep changing. No standard process can be written in advance for every situation. When a system values rule completeness but provides no route for feedback and correction, exceptions disappear from the process and move outside the system.", "That is why many functional issues return: users see incorrect permissions, invisible stores, or a process that cannot continue. What actually needs to be understood may be a change in organizational relationships, store ownership, or business responsibility."], quote: "A good process is not one without exceptions; it is one where exceptions can be identified, owned, and used to improve the rules.", sourceTitle: "An invisible store is a relationship problem", source: "By tracing organization–store relationships, proposing a relationship model, and coordinating business and engineering through launch, the issue moved from permission settings back to business relationships." },
    { title: "Responsibility Is Not a Status", label: "OWNERSHIP / NOT STATUS", paragraphs: ["Sales, distributors, functional teams, and engineering may all appear in one system. But unless it is clear who discovers, judges, handles, and feeds back an issue, status changes only replace communication; they do not create a real chain of ownership.", "Product design needs to make these relationships visible: give every issue a destination, let feedback return, and show managers which rules need adjustment. A system does not turn people into a process; it makes complex collaboration visible and adjustable."], quote: "A good system does not remove human judgment; it organizes judgment, collaboration, and ownership.", sourceTitle: "From a functional issue back to business relationships", source: "Requirements analysis, relationship modeling, engineering coordination, testing, launch, and follow-up ultimately solved more than a page; they repaired a chain of responsibility." },
  ], links: ["Expand SFA practice evidence ↗", "View permission governance evidence ↗", "Open project evidence space ↗"], conclusion: "The boundary of a system is not a lack of capability; it is that it cannot understand and coordinate on behalf of an organization.", ending: "Digital products should not turn everything into buttons. They should make business relationships clear, let standard processes run, give exceptions somewhere to go, and keep ownership moving forward.", boundary: "Company, brand, and internal system details are anonymized; this note abstracts from real project experience.", back: "← Back to work home", footer: "Before a process is written into a system, the business must understand it." },
  ja: { brand: "現代の仕事ノート", nav: "FMCG FIELD NOTES / 02", eyebrow: "FMCG BUSINESS & SYSTEM DESIGN", title: "システムは業務の完結ではない", question: "システム上の手順は正しいのに、現場ではなぜ説明や調整、迂回が必要になるのか。", judgment: "システムはプロセスを支えられても、それ自体でプロセスを生み出すことはできない。実際の業務には判断、例外対応、役割間の連携、責任の引き受けも含まれる。", asideTitle: "このノートのテーマ", asideBody: "システム上の手順が正しくても、なぜ現場では説明や調整、迂回が必要になるのか。", compareTitle: "システムが記録するのは手順。実際に業務を動かすのは関係性。", compareTag: "SYSTEM / PROCESS", systemLabel: "システム上のプロセス", systemHeading: "設定できる手順", realLabel: "実際のプロセス", realHeading: "組織が引き受ける関係性", system: [["申請", "項目を入力し、次のステップへ進む。"], ["承認", "ルールに従って割り当て、処理する。"], ["完了", "ステータスが終了に変わる。"]], real: [["判断", "これは何の問題で、このプロセスに入れるべきか。"], ["例外", "標準ルールで扱えないとき、誰が判断するのか。"], ["責任", "誰が結果を引き受け、変化を返し、調整を続けるのか。"]], sections: [
    { title: "判断はクリックではない", label: "判断 / クリックではない", paragraphs: ["システムは店舗の選択、項目の入力、承認申請を求められる。しかし、現場の問題が本当は何なのかまでは、通常わからない。実際の業務で最初に必要なのは「開始」を押すことではなく、問題が存在するのか、どの経路に進むのか、誰が関わるべきかを判断することだ。", "標準動作だけを固定の手順にすると、例外が起きたとき利用者は別の方法を探す。現場での相談、口頭確認、再申請、ルールを知る人への直接依頼などだ。システム上は完了していても、組織の判断力が高まったとは限らない。"], quote: "プロセスとは動作を並べることではなく、次に何をするのか、その理由を組織が理解できるようにすることだ。", sourceTitle: "複雑な店舗スコアリング", source: "店舗の陳列は SKU、棚の位置、陳列、価格、商品の経過日数を組み合わせて判断する。複雑な計算を現場へ移すだけでは、設定は完成しても判断の負担は減らない。" },
    { title: "例外はエラーではない", label: "例外 / エラーではない", paragraphs: ["チャネル、組織、店舗の関係は変わり続ける。標準プロセスですべての状況をあらかじめ書き切ることはできない。ルールの完全さだけを重視し、フィードバックと修正の入口を用意しないシステムでは、例外はプロセスから消え、システムの外へ移ってしまう。", "機能上の問題が繰り返される理由もそこにある。利用者に見えるのは権限の誤り、店舗が見えないこと、処理が進まないことだ。しかし本当に理解すべきなのは、組織関係、店舗の所属、業務上の責任が変わったことかもしれない。"], quote: "良いプロセスとは例外がないことではなく、例外を見つけ、引き受け、ルールの改善につなげられることだ。", sourceTitle: "見えない店舗の背後にある関係性", source: "組織と店舗の関係を特定し、関係モデルを改修し、業務と開発を調整してリリースまで進めることで、問題を権限設定から業務関係の問題へ戻して考えられた。" },
    { title: "責任はステータスではない", label: "責任 / ステータスではない", paragraphs: ["営業、代理店、機能部門、開発が一つのシステムに登場していても、誰が問題を発見し、判断し、処理し、フィードバックするのかが明確でなければ、ステータスの変化はコミュニケーションの代わりになるだけで、責任の連鎖は生まれない。", "プロダクト設計では、こうした関係性を見えるようにする必要がある。問題の行き先をつくり、フィードバックを戻し、どのルールを調整すべきかを管理者に伝える。システムは人をプロセスに変えるものではなく、複雑な協働関係を見える化し、継続的に調整できるようにするものだ。"], quote: "良いシステムは人の判断を消すのではなく、判断、協働、責任を組織化する。", sourceTitle: "機能の問題から業務関係へ", source: "要件整理、関係モデル、開発との調整、テスト、リリース、問題追跡を通じて、解決したのは一つの画面ではなく、責任の関係そのものだった。" },
  ], links: ["SFAの実践を見る ↗", "権限ガバナンスの証拠を見る ↗", "プロジェクトの証拠空間を開く ↗"], conclusion: "システムの限界は能力不足ではない。組織に代わって理解し、協働することはできないという点にある。", ending: "デジタルプロダクトが担うべきなのは、すべてをボタンに固定することではない。業務関係を明確にし、標準プロセスを動かし、例外を受け止め、責任を次の行動へつなぐことだ。", boundary: "会社名、ブランド名、社内システムの詳細は匿名化している。実際のプロジェクト経験をもとに、業界の論点として抽象化した。", back: "← 仕事のホームへ戻る", footer: "プロセスをシステムに書き込む前に、まず業務がそれを理解していなければならない。" },
};

export default function SystemProcessPage() {
  const locale = getRequestLocale();
  const text = copy[locale];
  return <main className={styles.page}>
    <nav className={styles.nav} aria-label="Field Notes navigation"><Link href="/" className={styles.brand}>{text.brand}</Link><span>{text.nav}</span><LanguageSwitcher locale={locale} pathname="/notes/system-process" /></nav>
    <header className={styles.hero}><div className={styles.number}>02</div><div><p className={styles.eyebrow}>{text.eyebrow}</p><h1>{text.title}</h1><h2>{text.judgment}</h2><p>{text.question}</p></div><aside className={styles.aside}><strong>{text.asideTitle}</strong><p>{text.asideBody}</p></aside></header>
    <section className={styles.compare}><div className={styles.sectionHead}><h2>{text.compareTitle}</h2><span>{text.compareTag}</span></div><div className={styles.compareGrid}><div className={styles.compareColumn}><h3><small>{text.systemLabel}</small>{text.systemHeading}</h3>{text.system.map(([title, body]) => <div className={styles.compareItem} key={title}><b>{title}</b><p>{body}</p></div>)}</div><div className={`${styles.compareColumn} ${styles.compareReal}`}><h3><small>{text.realLabel}</small>{text.realHeading}</h3>{text.real.map(([title, body]) => <div className={styles.compareItem} key={title}><b>{title}</b><p>{body}</p></div>)}</div></div></section>
    <article className={styles.essay}>{text.sections.map((section, index) => <section className={styles.section} key={section.title}><div className={styles.index}><strong>{String(index + 1).padStart(2, "0")}</strong><span>{section.label}</span></div><div className={styles.copy}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<p className={styles.quote}>{section.quote}</p></div><aside className={styles.source}><small>{locale === "en" ? `FIELD EVIDENCE / ${String(index + 1).padStart(2, "0")}` : locale === "ja" ? `実践の証拠 / ${String(index + 1).padStart(2, "0")}` : `实践来源 / ${String(index + 1).padStart(2, "0")}`}</small><h3>{section.sourceTitle}</h3><p>{section.source}</p><Link href="/cases/sfa" className={styles.sourceLink}>{text.links[index]}</Link></aside></section>)}</article>
    <section className={styles.ending}><div className={styles.mark}>→</div><div><h2>{text.conclusion}</h2><p>{text.ending}</p><p className={styles.boundary}>{text.boundary}</p></div></section>
    <footer className={styles.footer}><Link href="/">{text.back}</Link><span>{text.footer}</span></footer>
  </main>;
}
